spring:
  application:
    name: areteum-ddl

  # 실제 DB에는 손대지 않음
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none         # DB에는 실행하지 않음
            scripts:
              action: create-drop       # 스크립트 생성
              create-target: build/schema/mysql-create.sql
              drop-target: build/schema/mysql-drop.sql
            create-source: metadata
            drop-source: metadata
