INSERT INTO product (booth_id, name)
VALUES
    (20, '키링'),
    (21, '키링'),
    (21, '컵'),
    (21, '주얼리 트레이'),
    (22, '액세서리'),
    (22, '키링'),
    (22, '책갈피'),
    (23, '인형'),
    (23, '키링'),
    (24, '키링'),
    (25, '키링'),
    (25, '의료'),
    (25, '카드지갑'),
    (25, '티코스터'),
    (25, '줄감개'),
    (26, '에코백'),
    (26, '동전지갑'),
    (26, '텀블러 홀더'),
    (26, '스트링 파우치'),
    (26, '텀블러 가방'),
    (27, '키링'),
    (27, '컵'),
    (27, '스티커'),
    (27, '그릇'),
    (27, '곱창머리끈'),
    (28, '키링'),
    (28, '책갈피'),
    (28, '스티커'),
    (28, '연필'),
    (28, '틴케이스'),
    (28, '지우개'),
    (28, '핀버튼'),
    (29, '반지'),
    (29, '키링'),
    (29, '책갈피'),
    (29, '스티커'),
    (29, '팔찌'),
    (30, '끈갈피'),
    (31, '키링'),
    (31, '피규어'),
    (31, '코스터'),
    (31, '목걸이'),
    (31, '책갈피'),
    (31, '스티커'),
    (31, '머그컵'),
    (32, '휴대폰 고리'),
    (32, '틴케이스'),
    (32, '키링'),
    (32, '메모지'),
    (32, '비녀'),
    (32, '초미니 자석'),
    (32, '메지루시'),
    (32, '스티커'),
    (33, '키링'),
    (33, '백팩'),
    (33, '파우치'),
    (33, '네일체험'),
    (34, '엽서');

INSERT INTO menu (booth_id, price, name, note, category)
VALUES
    (35, 6000, '콘치즈', NULL, 'ANJU'),
    (35, 8000, '두부김치', NULL, 'ANJU'),
    (35, 8000, '오뎅탕', NULL, 'ANJU'),
    (35, 6000, '소시지볶음', NULL, 'ANJU'),
    (35, 7000, '떡볶이', NULL, 'ANJU'),
    (35, 0, '안주 최소 2개 이상 주문 시 술 무제한', NULL, 'EVENT'),
    (36, 9000, '김치우동', NULL, 'ANJU'),
    (36, 7000, '마라팽이당면', NULL, 'ANJU'),
    (36, 8000, '오꼬노미야끼', NULL, 'ANJU'),
    (36, 6000, '버터갈릭감자튀김', NULL, 'ANJU'),
    (36, 5000, '참치카나페', NULL, 'ANJU'),
    (36, 7000, '모듬소시지', NULL, 'ANJU'),
    (36, 6000, '메론소다', NULL, 'DRINK'),
    (36, 6000, '체리콕', NULL, 'DRINK'),
    (36, 6000, '레몬에이드', NULL, 'DRINK'),
    (37, 0, '오이&당근 쌈장', NULL, 'ANJU'),
    (37, 4000, '닭꼬치', NULL, 'ANJU'),
    (37, 5000, '어묵탕', NULL, 'ANJU'),
    (37, 3500, '치킨너겟', NULL, 'ANJU'),
    (37, 5000, '꿀토마토&치즈', NULL, 'ANJU'),
    (37, 3000, '감자탕컵라면', NULL, 'ANJU'),
    (38, 8000, '치즈불파게티(2인분)', NULL, 'ANJU'),
    (38, 6000, '메가밤스낵(워킹타코)', NULL, 'ANJU'),
    (38, 7000, '치즈계란말이', NULL, 'ANJU'),
    (38, 3000, '전남친 토스트(블루베리크림치즈토스트)', NULL, 'ANJU'),
    (38, 2000, '뿌링클호떡', NULL, 'ANJU'),
    (38, 3000, '강냉이', NULL, 'ANJU'),
    (38, 2000, '사이다', NULL, 'DRINK'),
    (38, 2000, '콜라', NULL, 'DRINK'),
    (38, 3000, '하이볼', NULL, 'ALCOHOL'),
    (39, 8000, '김치우동', NULL, 'ANJU'),
    (39, 8000, '묵사발', NULL, 'ANJU'),
    (39, 8000, '소시지&떡', NULL, 'ANJU'),
    (39, 3500, '팝쵸(팝콘 + 나쵸)', NULL, 'ANJU'),
    (39, 8000, '잃어버린 카드(카드형 멀티툴)', NULL, 'ETC'),
    (40, 5000, '김치전', NULL, 'ANJU'),
    (40, 4000, '나쵸', NULL, 'ANJU'),
    (40, 6000, '오뎅탕', NULL, 'ANJU'),
    (40, 6000, '소시지볶음', NULL, 'ANJU'),
    (40, 5500, '아이스크림 팬케이크', NULL, 'ANJU'),
    (40, 0, '15,000원 이상 주문 시 주류 한 병 제공', NULL, 'EVENT'),
    (41, 7000, '타코야끼', NULL, 'ANJU'),
    (41, 6500, '교자', NULL, 'ANJU'),
    (41, 6000, '치킨 가라아게', NULL, 'ANJU'),
    (41, 1500, '뻥튀기 小', NULL, 'ANJU'),
    (41, 2000, '뻥튀기 中', NULL, 'ANJU'),
    (41, 2000, '펩시 제로 라임', NULL, 'DRINK'),
    (46, 2500, '1회', '계좌이체만 가능', 'ETC'),
    (49, 6000, '1+1', '카드 결제 가능', 'ETC'),
    (53, 4000, '소프트아이스크림 바닐라', NULL, 'FT'),
    (53, 5000, '소프트아이스크림 딸기', NULL, 'FT'),
    (53, 5000, '소프트아이스크림 초코', NULL, 'FT'),
    (53, 5000, '소프트아이스크림 인절미', NULL, 'FT'),
    (53, 5000, '소프트아이스크림 흑임자', NULL, 'FT'),
    (54, 5000, '회오리감자', NULL, 'FT'),
    (54, 5000, '닭꼬치', NULL, 'FT'),
    (55, 5000, '떡볶이', NULL, 'FT'),
    (55, 5000, '찰순대', NULL, 'FT'),
    (55, 3000, '어묵(2p)', NULL, 'FT'),
    (55, 5000, '어묵(4p)', NULL, 'FT'),
    (56, 10000, '닭강정(중)', NULL, 'FT'),
    (56, 15000, '닭강정(대)', NULL, 'FT'),
    (57, 10000, '소고기불초밥', NULL, 'FT'),
    (57, 10000, '새우초밥', NULL, 'FT'),
    (58, 10000, '크림/칠리새우(중)', NULL, 'FT'),
    (58, 15000, '크림/칠리새우(대)', NULL, 'FT');

INSERT INTO set_menu (booth_id, name)
VALUES
    (39, 'A세트'),
    (39, 'B세트'),
    (41, '맥주set'),
    (41, '하이set');

INSERT INTO set_menu_variant (set_menu_id, price, note)
VALUES
    ((SELECT id FROM set_menu WHERE booth_id = 39 AND name = 'A세트'), 27500, '첫 주문은 세트 주문 필수'),
    ((SELECT id FROM set_menu WHERE booth_id = 39 AND name = 'B세트'), 21000, '첫 주문은 세트 주문 필수'),
    ((SELECT id FROM set_menu WHERE booth_id = 41 AND name = '맥주set'), 13000, '주문 시 맥주 2잔 증정'),
    ((SELECT id FROM set_menu WHERE booth_id = 41 AND name = '맥주set'), 12500, '주문 시 맥주 2잔 증정'),
    ((SELECT id FROM set_menu WHERE booth_id = 41 AND name = '맥주set'), 18500, '주문 시 맥주 3잔 증정'),
    ((SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set'), 14000, '주문 시 하이볼 2잔 증정'),
    ((SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set'), 13500, '주문 시 하이볼 2잔 증정'),
    ((SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set'), 19000, '주문 시 하이볼 3잔 증정');

INSERT INTO set_menu_variant_items (variant_id, item_name)
VALUES
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 39 AND name = 'A세트') AND price = 27500), '김치우동'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 39 AND name = 'A세트') AND price = 27500), '묵사발'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 39 AND name = 'A세트') AND price = 27500), '소시지&떡'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 39 AND name = 'A세트') AND price = 27500), '팝쵸(팝콘 + 나쵸)'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 39 AND name = 'B세트') AND price = 21000), '김치우동'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 39 AND name = 'B세트') AND price = 21000), '소시지&떡'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 39 AND name = 'B세트') AND price = 21000), '설탕토마토'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '맥주set') AND price = 13000), '타코야끼'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '맥주set') AND price = 13000), '교자'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '맥주set') AND price = 12500), '타코야끼'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '맥주set') AND price = 12500), '가라아게'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '맥주set') AND price = 18500), '타코야끼'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '맥주set') AND price = 18500), '교자'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '맥주set') AND price = 18500), '가라아게'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set') AND price = 14000), '타코야끼'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set') AND price = 14000), '교자'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set') AND price = 14000), '뻥튀기 小'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set') AND price = 13500), '타코야끼'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set') AND price = 13500), '가라아게'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set') AND price = 13500), '뻥튀기 小'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set') AND price = 19000), '타코야끼'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set') AND price = 19000), '교자'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set') AND price = 19000), '가라아게'),
    ((SELECT id FROM set_menu_variant WHERE set_menu_id = (SELECT id FROM set_menu WHERE booth_id = 41 AND name = '하이set') AND price = 19000), '뻥튀기 中');