name: Deploy Backend (main → production) # main 배포용

on:
  push:
    branches: [ main ]

jobs:
  deploy-prod-backend: # job 이름 변경
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SSH build & restart backend on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail

            # worktree 존재/정상 여부 판단: .git은 파일(-f)이어야 함
            if [ -f /srv/festival-backend/.git ]; then
              cd /srv/festival-backend
              git fetch origin
              git reset --hard origin/main
            else
              # 깨져있을 수 있으니 정리 후 재생성
              rm -rf /srv/festival-backend || true 
              cd /srv/2025ARETEUM-BackEnd
              git fetch --all --prune
              git worktree prune
              git worktree add /srv/festival-backend origin/main 
            fi

            cd /srv/festival-backend # 경로 변경
            docker-compose -p areteum-prod build backend
            docker-compose -p areteum-prod up -d backend 

            docker-compose -p areteum-prod ps # 경로 변경
            docker-compose -p areteum-prod logs --tail=100 backend || true 
